# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af37491d6052c6102543aee47950f5a18a6d712155e6be2b7e5604c06704a145d5ce992ae38c4fc104b720c3eb4c0083181bed98e3b1b8a5f7473671b677296c

test:
  secret_key_base: 1e97cfaa3bc8e91a595fcb13c50e07d322aa317583fa1107b2dda2e078cabadfc6b7adc424ac7232633f8306f680f8c3d623b1b19cd761f724d76ba036b893b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
