toolbar:
  - styleselect | bold italic | undo redo | alignjustify | bullist numlist outdent indent
  - image | link | codesample | code | forecolor backcolor
plugins:
  - image
  - link
  - codesample
  - code
  - advlist
  - autolink
  - lists
  - charmap
  - hr
  - anchor
  - pagebreak
  - textcolor
  - colorpicker
  - textpattern
  - imagetools
